### PR TITLE
Partial indentation support for v1.3 mustache

### PR DESCRIPTION
**Pull request by agentgt**
@samskivert I think this indentation is cleaner than the previous commit.

For one it doesn't break API.

It doesn't use weird regex.

And the most important part is it will help me do inheritance.

### CODE REVIEW

**Comment by samskivert** [comment]
Works for me! :)

**Comment by agentgt** [comment]
BTW while I have you I am big fan. I have kind of followed you through the years as you have great content on your website (yes I know that sounds creepy... sorry). I particularly like your PIM and your game development writing.

**Comment by samskivert** [comment]
Thanks!

Now for some bad news, it looks like some of the tests the other guy wrote fail with your patch. I've changed spaces to `.` and tab to `↦` to make this more visible, but here's an example:

```
----- Expected -----
\
↦1
↦↦2
↦↦a

↦↦b
↦↦2
↦1
/

----- Got -----
\
↦1
↦↦2
↦↦a
↦↦
↦↦b
↦↦2
1
/

```

and here's another:

```
----- Expected -----
|
.1
..2
..<
->
..2
.1
|

----- Got -----
|
.1
..2
..<
->
..2
1
|

```

It looks like in the first case, there's a line that should maybe be blank but is being indented? Not sure what the Mustache spec would say in that case. The second one seems to fail to indent the last `1` which seems perhaps more problematic. I can try to correlate these with the original test cases. Maven makes that annoyingly difficult because it saves up test failures while running the tests and then doesn't report things until much later.

**Comment by agentgt** [comment]
I have another commit where I updated the unit test framework stuff so it works with maven and indeed the IDE did not run the tests correctly.

**Comment by samskivert** [comment]
It looks like the Mustache spec (which is pretty minimal) does not weigh in on whether blank lines inside partials should be indented or not. Given its flexibility, I think not indenting them is probably nicest, because then you don't end up with a bunch of trailing whitespace if you're using Mustache to generate code for example. The second problem may be related to using CRLF instead of just LF. I'm looking at that one right now, but I got side tracked looking into converting the test code to use triple quoted strings so that I can see what the heck all these newline filled test cases are even trying to do.

**Comment by agentgt** [comment]
Yes that is correct. I have update the test framework to work in another branch but there were so many commits after that branch that I could not integrate them. 

Give me ten minutes and I will rebase it into master

**Comment by samskivert** [comment]
Sounds good. I think the second test was not CRLF related but actually nested partials where the outer partial further indents the inner partial.

**Comment by agentgt** [comment]
I see what you mean with Maven. I'm using eclipse and intellij (I switch back and forth) and just run it from there.

The spec tests I do all sort of show whitespace magic that someone else did before but the regular tests alas do not make it as clear.

**Comment by agentgt** [comment]
Just by my brief playing around with the Wontache (https://jgonggrijp.gitlab.io/wontache/playground.html) which is pseudo reference mustache implementation it appends spaces regardless if the line is empty (only having `\n`) or not.

**Comment by agentgt** [comment]
@samskivert sorry I couldn't really respond as well as I would have liked last night as I was heading out the door:

> It looks like the Mustache spec (which is pretty minimal) does not weigh in on whether blank lines inside partials should be indented or not. Given its flexibility, I think not indenting them is probably nicest, because then you don't end up with a bunch of trailing whitespace if you're using Mustache to generate code for example.

Per the spec:

```
  Partial tags SHOULD be treated as standalone when appropriate.  If this tag
  is used standalone, any whitespace preceding the tag should treated as
  indentation, and prepended to each line of the partial before rendering.
```

"*and prepended to each line of the partial before rendering.*"

It appears most implementations including my own (not JMustache but [jstachio](https://github.com/jstachio/jstachio)) follow that explicitly.

We could certainly explore making that configurable though and I agree on your points!

> I'm looking at that one right now, but I got side tracked looking into converting the test code to use triple quoted strings so that I can see what the heck all these newline filled test cases are even trying to do.

Yes I was planning on porting some of the original unit tests to the new parameterized spec runner. The old spec runner was before JUnit parameterized.

Then we can just put the test in YAML just like the spec (I know I hate YAML but it for this its pretty good).

The spec test inserts meta whitespace characters (like you did in your comments) when a test fails. There was some work started by another that did this but I hopefully improved on that (as well as add parameterization).

Anyway I'm here to help for the long haul as JStachio and modern Spring Boot rely on JMustache. So if the original tests that are failing are correct I will fix them shortly (hopefully monday).

In the meantime I was going to fix the build so that we have github actions that show unit tests etc. You may have to do something on your end on the github repo to allow publishing unit tests that will look something like: https://github.com/jstachio/jstachio/actions/runs/6902369992/job/18778997865. 

I will let you know by Monday.

Cheers

**Comment by samskivert** [comment]
Thanks for the test bits. I'm fine with the default behavior being to uniformly indent partials regardless of whether they are themselves generating blank lines. If you or I feel ambitious we can add an option to preserve the blank lines in that case with no trailing whitespace. I do think nested partials should be properly doubly indented, so I think that is still an issue with your patch. And if you want to convert the JUnit tests the other guy added to YAML that's certainly fine with me. I agree the error reporting is much better for those cases. It's just probably fiddly to add additional YAML tests that are not in the git module that pulls in the standard YAML tests...

**Comment by samskivert** [comment]
Looks like it ran the tests, and the ones I saw failing earlier are failed:

https://github.com/samskivert/jmustache/runs/18816910562

So the test running is working! :)

**Comment by agentgt** [comment]
> I do think nested partials should be properly doubly indented, so I think that is still an issue with your patch.

Yes that is probably a bug. I was planning on having that part more tested and whatnot but I jumped the gun on pushing the PR so that I could get the other stuff like test infrastructure in. I'm fairly sure I know what is wrong.

I do apologize about that. I will get it fixed very soon!

>  It's just probably fiddly to add additional YAML tests that are not in the git module that pulls in the standard YAML tests..

Yes I'm going to move the test infrastructure to an abstract class or something like that.

**Pull request merged**
